name: Update add-on repository

on:
  repository_dispatch:
    types: [update-repo]
  workflow_dispatch:

permissions: write-all

jobs:
  update-repo:
    name: Update repository
    runs-on: ubuntu-latest

    env:
      GIT_USER_NAME: Alfa Update Bot
      GIT_USER_EMAIL: alfa-add-on@users.noreply.github.com

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Generating repo
        run: |
          cd ${{ github.workspace }}
          sh gen_repo.sh
